sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sanketh1701/simpleflask-2020 -f Dockerfile.dev .

script:
   - docker run sanketh1701/simpleflask-2020 pytest